version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    depends_on:
      - db
    #environment:
    ports:
      - "8000:8000"
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: db2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: DESKTOP-UIBJPQB
    ports:
      - "3306:3306"
    networks:
      - app_network

networks:
  app_network:
