version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    depends_on:
      - db
    #environment:
    ports:
      - "8000:8000"
    networks:
      - app_network

  db2:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db2
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    networks:
      - app_network

networks:
  app_network:
